<div class="container d-flex justify-content-center">
    <form enctype='multipart/form-data' method='POST'>
        <div class="form-group mb-2">
            <div><label>Select a .csv, .xlsx or .xls file</label></div>
            <input type="file" class="form-control-file" name='imported_file' accept=".xlsx, .xls, .csv" required />
        </div>
        <input class="btn btn-primary" type='submit' name='upload' value='Upload'/>
    </form>
</div>

